import React from "react"
import { Button } from "@chakra-ui/react"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/mgzCV3zD3iWpctEI6UoUhB/?node-id=148-1720",
  {
    props: {
      iconStart: figma.boolean(".iconStart?"),
      iconStart: figma.instance("iconStart"),
      iconEnd: figma.boolean(".iconEnd?"),
      iconEnd: figma.instance("iconEnd"),
      label: figma.string("label"),
    },
    example: (props) => <Button />,
  },
)
